# Generated by Django 3.0 on 2022-10-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('des', models.TextField()),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='pro')),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=12)),
                ('Last_Name', models.CharField(max_length=12)),
                ('email_id', models.EmailField(max_length=254)),
                ('mobile_no', models.PositiveIntegerField()),
                ('password', models.CharField(max_length=8)),
            ],
        ),
    ]
