# Generated by Django 3.0 on 2022-12-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='fpro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('img', models.ImageField(upload_to='pro')),
            ],
        ),
    ]
